### ISSUE TITLE
Fix hover text on exhibition archive images

### ISSUE THREAD

**Issue by koreoliver** [willis-meyers/aggregatespace#5]
- Center text and make it larger
- Remove hover text
- Can't access navbar on hover because title box overlaps navbar  

Need to look at:
1. CSS
2. Adding it to all the gallery items

**Comment by koreoliver** [comment]
Added hover titles to all of the archives. I centered the text on the titles and made it larger. Did you want a margin above the text? Some of the titles are much longer so if I center the shorter ones (from the top) the text on the longer titles bleeds out of the archive image. Not sure yet if there is a better way to do this. You also want the yellow hover text box removed from each archive correct?

**Comment by willis-meyers** [comment]
Awesome! @koreoliver  I will check it out re: titles overflowing. The hover text can be removed.

**Comment by willis-meyers** [comment]
@koreoliver - very nice! re: tooltips/default hover text: I dug around a little more and found it is tricky with the markup/JS plugin we have as it would require us to change the way we are dealing with titles altogether. I created workaround for now so the default tooltip doesn't appear on hover. Closing issue.
