### ISSUE TITLE
FOOTER: include social media links

### ISSUE THREAD

**Issue by willis-meyers** [willis-meyers/aggregatespace#6]
Reference content in contact.html
"Back to top" only appears on hover. On the contact page it always appears.

**Comment by koreoliver** [comment]
@willis-meyers Added social media links to the footer but like the "Back to top" link they only appear on hover. Will look at removing hover effect from both.

**Comment by willis-meyers** [comment]
Thanks @koreoliver - I will check it out tonight!

**Comment by koreoliver** [comment]
@willis-meyers Fixed social media icons and "Back to top" in footer so now they always appear

**Comment by willis-meyers** [comment]
Looking good @koreoliver - Closing out the issue.
